export const EMPTY_PLACEHOLDER = '---'
export const DUPLICATE_VAR = 'duplicate'
export const EDIT_VAR = 'edit'
export const IMAGE_HOST_NAME = 'https://ik.imagekit.io/g5zld5ryd'
export const GITHUB_PROFILE = 'https://github.com/kamalesh777'
export const LINKEDIN_PROFILE = 'https://www.linkedin.com/in/kamalesh-maity-46679586/'
